[build]
  publish = "."

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/riskdash.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
